// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atyzwfoljiiablljijjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0eXp3Zm9samlpYWJsbGppampoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjQyNjEsImV4cCI6MjA2NDUwMDI2MX0.c4bWA_mpJAz3hGZarQ1JEAFayQu5g3tz-IfYIyHdiFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);